name: build

on: [push]

jobs:

  staticAnalysis:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
        
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Decode google-services.json
        shell: bash
        env:
          FIREBASE_CONFIG_ADMIN: ${{ secrets.FIREBASE_CONFIG_ADMIN }}
          FIREBASE_CONFIG_USER: ${{ secrets.FIREBASE_CONFIG_USER }}
        run: 'echo "$FIREBASE_CONFIG_ADMIN" | tee app/src/admin/debug/google-services.json app/src/admin/release/google-services.json && echo "$FIREBASE_CONFIG_USER" | tee app/src/user/debug/google-services.json app/src/user/release/google-services.json '
        
      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Static Analysis
        run: ./gradlew ktlintAdminDebugCheck detekt app:lintAdminDebug && ./gradlew ktlintUserDebugCheck detekt app:lintUserDebug

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Decode google-services.json
        shell: bash
        env:
          FIREBASE_CONFIG_ADMIN: ${{ secrets.FIREBASE_CONFIG_ADMIN }}
          FIREBASE_CONFIG_USER: ${{ secrets.FIREBASE_CONFIG_USER }}
        run: 'echo "$FIREBASE_CONFIG_ADMIN" | tee app/src/admin/debug/google-services.json app/src/admin/release/google-services.json && echo "$FIREBASE_CONFIG_USER" | tee app/src/user/debug/google-services.json app/src/user/release/google-services.json '

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Build all configurations
        run: ./gradlew assembleAdminDebug && ./gradlew assembleUserDebug
